In [23]:
#Natasha Roy
#BIOE 485 HW2 - Problem 4 Calculation

import numpy as np
import numpy.linalg as la
from scipy.linalg import qr

print("BIOE 485: Homework 2 - Problem 4")
print("Orthogonal Projection and Distance in R^5")
print("="*50)

BIOE 485: Homework 2 - Problem 4
Orthogonal Projection and Distance in R^5


In [24]:
#Define basis vectors for subspace U
u1=np.array([1,2,4,-1,6])
u2=np.array([0,-2,0,3,1])
u3=np.array([-1,1,2,0,-1])
u4=np.array([1,3,-2,0,1])

#Define vector x
x=np.array([1,1,1,1,1])

#Create basis matrix B (columns are basis vectors)
B=np.column_stack([u1,u2,u3,u4])

print("Basis vectors for subspace U:")
print(f"u1={u1}")
print(f"u2={u2}")
print(f"u3={u3}")
print(f"u4={u4}")
print(f"\nVector x = {x}")
print(f"\nBasis matrix B (columns are basis vectors):")
print(B)


Basis vectors for subspace U:
u1=[ 1  2  4 -1  6]
u2=[ 0 -2  0  3  1]
u3=[-1  1  2  0 -1]
u4=[ 1  3 -2  0  1]

Vector x = [1 1 1 1 1]

Basis matrix B (columns are basis vectors):
[[ 1  0 -1  1]
 [ 2 -2  1  3]
 [ 4  0  2 -2]
 [-1  3  0  0]
 [ 6  1 -1  1]]


In [25]:
#Check if basis vectors are linearly independent
rank_B=la.matrix_rank(B)
num_vectors=B.shape[1]
space_dim=B.shape[0]

print(f"Linear Independence Check:")
print(f"Rank of B: {rank_B}")
print(f"Number of basis vectors: {num_vectors}")
print(f"Space dimension: {space_dim}")
print(f"Vectors are linearly independent: {rank_B == num_vectors}")

if rank_B!=num_vectors:
    print("WARNING: Basis vectors are not linearly independent!")
else:
    print("Basis vectors form a valid basis for U")


Linear Independence Check:
Rank of B: 4
Number of basis vectors: 4
Space dimension: 5
Vectors are linearly independent: True
Basis vectors form a valid basis for U


In [26]:
print("\n"+"="*60)
print("PART (a): ORTHOGONAL PROJECTION")
print("="*60)

#Method 1: Direct projection formula P_U(x)=B(B^T B)^(-1) B^T x
print("Method 1: Direct Projection Formula")
print("P_U(x)=B(B^T B)^(-1) B^T x")

#Calculate B^T B
BTB=B.T @ B
print(f"\nB^T B=")
print(BTB)

#Calculate (B^T B)^(-1)
BTB_inv=la.inv(BTB)
print(f"\n(B^T B)^(-1)=")
print(BTB_inv)

#Calculate projection
projection_direct=B @ BTB_inv @ B.T @ x
print(f"\nProjection P_U(x) = {projection_direct}")

#Method 2: QR decomposition
print(f"\n"+"-"*40)
print("Method 2: QR Decomposition")
print("B = QR where Q has orthonormal columns")

Q,R=qr(B)
projection_qr=Q@(Q.T@x)

print(f"\nQ (orthonormal basis):")
print(Q)
print(f"\nProjection using QR: P_U(x) = QQ^T x")
print(f"P_U(x) = {projection_qr}")

#Verify both methods give same result
print(f"\nMethods agree: {np.allclose(projection_direct,projection_qr)}")
print(f"Difference: {la.norm(projection_direct-projection_qr):.2e}")

#Use more stable QR result
proj_x=projection_qr



PART (a): ORTHOGONAL PROJECTION
Method 1: Direct Projection Formula
P_U(x)=B(B^T B)^(-1) B^T x

B^T B=
[[58 -1  3  5]
 [-1 14 -3 -5]
 [ 3 -3  7 -3]
 [ 5 -5 -3 15]]

(B^T B)^(-1)=
[[ 0.01893453 -0.00609756 -0.01564506 -0.01147304]
 [-0.00609756  0.10365854  0.06859756  0.05030488]
 [-0.01564506  0.06859756  0.20890164  0.0698612 ]
 [-0.01147304  0.05030488  0.0698612   0.10123155]]

Projection P_U(x) = [0.13350449 1.         0.72272144 0.89602054 1.31193838]

----------------------------------------
Method 2: QR Decomposition
B = QR where Q has orthonormal columns

Q (orthonormal basis):
[[-1.31306433e-01  4.61079248e-03  4.20137886e-01 -6.25368935e-02
  -8.95717955e-01]
 [-2.62612866e-01 -5.25630343e-01 -1.93263428e-01 -7.85745807e-01
   5.55111512e-17]
 [-5.25225731e-01  1.84431699e-02 -7.24614284e-01  3.41431265e-01
  -2.86629746e-01]
 [ 1.31306433e-01  7.97667099e-01 -2.72842486e-01 -5.10381744e-01
  -1.07486155e-01]
 [-7.87838597e-01  2.95090719e-01  4.32000603e-01 -4.03463829e-02

In [27]:
print("\n"+"="*60)
print("PART (b): DISTANCE CALCULATION")
print("="*60)

#Calculate distance vector and distance
distance_vector=x-proj_x
distance=la.norm(distance_vector)

print(f"Original vector x = {x}")
print(f"Projection P_U(x) = {proj_x}")
print(f"Distance vector (x-P_U(x)) = {distance_vector}")
print(f"\nDistance from x to U:")
print(f"d(x,U)=||x-P_U(x)||={distance:.6f}")

#Individual components
print(f"\nComponent breakdown:")
print(f"x[0] - P_U(x)[0] = {x[0]} - {proj_x[0]:.6f} = {distance_vector[0]:.6f}")
print(f"x[1] - P_U(x)[1] = {x[1]} - {proj_x[1]:.6f} = {distance_vector[1]:.6f}")
print(f"x[2] - P_U(x)[2] = {x[2]} - {proj_x[2]:.6f} = {distance_vector[2]:.6f}")
print(f"x[3] - P_U(x)[3] = {x[3]} - {proj_x[3]:.6f} = {distance_vector[3]:.6f}")
print(f"x[4] - P_U(x)[4] = {x[4]} - {proj_x[4]:.6f} = {distance_vector[4]:.6f}")



PART (b): DISTANCE CALCULATION
Original vector x = [1 1 1 1 1]
Projection P_U(x) = [1. 1. 1. 1. 1.]
Distance vector (x-P_U(x)) = [-4.44089210e-16  0.00000000e+00 -2.22044605e-16  1.11022302e-16
  0.00000000e+00]

Distance from x to U:
d(x,U)=||x-P_U(x)||=0.000000

Component breakdown:
x[0] - P_U(x)[0] = 1 - 1.000000 = -0.000000
x[1] - P_U(x)[1] = 1 - 1.000000 = 0.000000
x[2] - P_U(x)[2] = 1 - 1.000000 = -0.000000
x[3] - P_U(x)[3] = 1 - 1.000000 = 0.000000
x[4] - P_U(x)[4] = 1 - 1.000000 = 0.000000
